# 工作流名称，会在 GitHub UI 中显示
name: Deploy static content to Pages

# 定义触发工作流的事件
on:
  # 允许手动触发工作流
  workflow_dispatch:
  # 当推送到 main 分支时触发
  push:
    branches: [ main ]

# 设置工作流权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时运行一个部署
concurrency:
  group: "pages"
  cancel-in-progress: false

# 定义工作流中的作业 (jobs)
jobs:
  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # 指定作业运行的环境
    runs-on: ubuntu-latest
    
    # 定义作业中的步骤
    steps:
      # 检出代码仓库
      - name: Checkout
        uses: actions/checkout@v4
      
      # 构建静态文件
      - name: Build static files
        run: |
          mkdir -p _site
          cp -r src/main/resources/templates/* _site/
          echo "构建完成，准备部署到 GitHub Pages"
      
      # 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      
      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      # 显示部署完成信息
      - name: Deployment completed
        run: |
          echo "=========================================="
          echo "GitHub Pages 部署说明"
          echo "=========================================="
          echo "部署已完成！"
          echo ""
          echo "请访问以下地址查看您的网站："
          echo "https://bliua.github.io/fortest/"
          echo ""
          echo "如果页面无法访问，请检查："
          echo "1. GitHub Pages 是否已在仓库设置中启用"
          echo "2. 仓库设置中的 Pages 源是否设置为 GitHub Actions"
          echo "3. 您的用户名和仓库名是否正确"
          echo "=========================================="